// Shared between ali-instructions-global and ali-instructions-project.
// Every file these skills generate carries an HTML-comment marker; this module
// builds and parses them, strips `<!-- only: agent -->` blocks and handles the
// Karpathy block fences.

import { sha256 } from './fsx.js';

export const GENERATED_RE =
  /<!--\s*generated by (instructions-global|instructions-project) from (\S+) \| run (\S+) \| sha256 ([0-9a-f]{64}) \|[^>]*-->/;

export function generatedMarker({ skill, source, runId, hash, hint }) {
  const tail = hint ?? `edit the master, then run ${skill} --sync-only`;
  return `<!-- generated by ${skill} from ${source} | run ${runId} | sha256 ${hash} | ${tail} -->`;
}

export function parseGeneratedMarker(text) {
  const m = GENERATED_RE.exec(text);
  return m ? { skill: m[1], source: m[2], runId: m[3], hash: m[4] } : null;
}

export const SHIM_RE = /<!--\s*instructions-project: shim; canonical AGENTS\.md sha256 ([0-9a-f]{64})\s*-->/;
export function shimMarker(hash) {
  return `<!-- instructions-project: shim; canonical AGENTS.md sha256 ${hash} -->`;
}
export function parseShimMarker(text) {
  const m = SHIM_RE.exec(text);
  return m ? { hash: m[1] } : null;
}

/**
 * Keep `<!-- only: a,b -->…<!-- /only -->` blocks whose agent list contains
 * `agent` (tags removed), drop the others entirely. Nested blocks unsupported.
 */
export function stripOnlyBlocks(text, agent) {
  const re = /<!--\s*only:\s*([a-z0-9_,\-\s]+?)\s*-->\r?\n?([\s\S]*?)<!--\s*\/only\s*-->\r?\n?/g;
  return text.replace(re, (whole, list, body) => {
    const agents = list.split(/[,\s]+/).filter(Boolean);
    return agents.includes(agent) ? body : '';
  });
}

/** Content hash used in markers: normalised body (LF, single trailing newline). */
export function contentHash(text) {
  return sha256(text.replace(/\r\n?/g, '\n').replace(/\s+$/, '') + '\n');
}

// --- Karpathy block -------------------------------------------------------

export const KARPATHY_BEGIN_RE =
  /<!--\s*karpathy-guidelines: begin source=(\S+) ref=(\S+) sha256=([0-9a-f]{64})\s*-->/;
export const KARPATHY_END = '<!-- karpathy-guidelines: end -->';

export function karpathyBegin({ source, ref, hash }) {
  return `<!-- karpathy-guidelines: begin source=${source} ref=${ref} sha256=${hash} -->`;
}

/** Locate the block: {start, end, header:{source,ref,hash}, body} or null. */
export function findKarpathyBlock(text) {
  const begin = KARPATHY_BEGIN_RE.exec(text);
  if (!begin) return null;
  const endIdx = text.indexOf(KARPATHY_END, begin.index);
  if (endIdx === -1) return { start: begin.index, end: -1, header: headerOf(begin), body: null, broken: true };
  const bodyStart = begin.index + begin[0].length;
  const body = text.slice(bodyStart, endIdx).replace(/^\r?\n/, '').replace(/\s+$/, '');
  return {
    start: begin.index,
    end: endIdx + KARPATHY_END.length,
    header: headerOf(begin),
    body,
    bodyHash: contentHash(body)
  };
}

function headerOf(m) {
  return { source: m[1], ref: m[2], hash: m[3] };
}

/** Text with the block replaced (or appended when absent). */
export function putKarpathyBlock(text, { source, ref, hash, body }) {
  const block = `${karpathyBegin({ source, ref, hash })}\n${body.trim()}\n${KARPATHY_END}`;
  const found = findKarpathyBlock(text);
  if (found && !found.broken) {
    return text.slice(0, found.start) + block + text.slice(found.end);
  }
  const base = text.replace(/\s+$/, '');
  return `${base}${base ? '\n\n' : ''}${block}\n`;
}

/** Text without the block (and without the blank lines that surrounded it). */
export function removeKarpathyBlock(text) {
  const found = findKarpathyBlock(text);
  if (!found || found.broken) return text;
  const rest = text.slice(found.end).replace(/^\s+/, '');
  const head = text.slice(0, found.start).replace(/\s+$/, '');
  return `${head}${rest ? `\n\n${rest}` : ''}`.replace(/\s+$/, '') + '\n';
}
