import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));

export const pkg = JSON.parse(
  readFileSync(join(packageRoot, 'package.json'), 'utf8')
);

/** Every published skill gets this prefix. `review-branch` -> `ali-review-branch`. */
export const PREFIX = 'ali-';

/** Marker file dropped into each installed skill, so updates only touch what we own. */
export const MARKER = '.ali-agent-kit.json';

/** Bump when the marker layout changes; older markers stop counting as ours. */
export const MARKER_SCHEMA_VERSION = 1;

/** Source dir inside the package that holds the skills. */
export const skillsSourceDir = join(packageRoot, 'skills');

/**
 * Sentinel opening the managed-file notice. It is what lets `buildSkill` spot a
 * notice in a *source* skill and reject it — the way an installed copy pasted
 * back into `skills/` as a starting point would otherwise ship with two.
 * Installing twice cannot stack notices in any case: every install rewrites
 * SKILL.md from the source, and nothing ever reads the installed file.
 */
export const NOTICE_SENTINEL = '<!-- ali-agent-kit: managed file -->';

/**
 * Prepended to every installed SKILL.md, right after the frontmatter. Agents
 * read the whole file, so it doubles as an instruction not to patch the copy.
 */
export const INSTALL_NOTICE = [
  NOTICE_SENTINEL,
  '',
  '> **This skill ships with the [ali-agent-kit](https://github.com/pravbeseda/ali-agent-kit) package.**',
  '> Do not edit this file in place: the next `ali-agent-kit install` replaces it and every local change is lost.',
  '> Change the skill in the ali-agent-kit repository and release it from there instead.',
  ''
].join('\n');
